name: Container
on: push

jobs:
  drawio-docker:
    runs-on: ubuntu-latest
    container:
      image: truecharts/drawio
    steps:
      - uses: actions/checkout@v3
      - name: Build png images
        run: |
          cat /etc/os-release
          ls -al > hoge.txt
      
      - name: "Upload Failed Tests' Diffs"
        uses: actions/upload-artifact@v3
        with:
          path: output