name: Container
on: push

jobs:
  drawio-docker:
    runs-on: ubuntu-latest
    container:
      image: truecharts/drawio
    steps:
      - uses: actions/checkout@v3

      - name: Build png images
        run: |
          mkdir -p output
          date +%Y/%m/%H:%M:%s > output/$(date +%Y%m%H:%M:%s).txt

  git:
    runs-on: ubuntu-latest
      - name: Install Git
        run: |
          apt-get update
          apt-get install -y git

      - name: Commit images
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "Github Action"
          git add -A
          git commit -m "Image built." -a
      
      - name: Push changes
        uses: ad-m/github-push-action@master
        with: 
          github_token: ${{ secrets.GITHUB_TOKEN }}
