name: Container
on: push

jobs:
  drawio-docker:
    runs-on: ubuntu-latest
    container:
      image: truecharts/drawio
    steps:
      - uses: actions/checkout@v3
      - name: Build png images
        run: |
          mkdir -p artifact
          cd artifact
          ls -al
          echo hoge > hoge.txt
      
      - name: "Upload Failed Tests' Diffs"
        uses: actions/upload-artifact@v3
        with:
          path: artifact
          if-no-files-found: error