name: Container
on: push

jobs:
  drawio-docker:
    runs-on: ubuntu-latest
    container:
      image: truecharts/drawio
    steps: #dockerコンテナ内でステップを実行
      - name: Build png images
        run: |
          cat /etc/os-release
          ls -al